language: java
script: mvn package docker:build docker:push
sudo: required
services:
  - docker
before_install:
  - docker --version
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
